# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#

fail_fast: false
default_stages: [commit, push]
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    # https://pre-commit.com/hooks.html
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-shebang-scripts-are-executable
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: pytest
        name: run python3 unit tests for xtf-runner
        entry: env PYTHONDEVMODE=yes python3 -m pytest -v -rA
        pass_filenames: false
        language: python
        types: [python]
        additional_dependencies: [pytest]

-   repo: local
    hooks:
    -   id: git-diff # For reference: https://github.com/pre-commit/pre-commit/issues/1712
        name: Show not staged changes (fixups may make them too)
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true
