# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#

fail_fast: false
default_stages: [commit, push]
repos:

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    # https://pre-commit.com/hooks.html
    hooks:
    -   id: check-merge-conflict
    -   id: check-yaml
    -   id: debug-statements
    -   id: mixed-line-ending
        args: ['--fix=lf']
    -   id: trailing-whitespace

-   repo: local
    hooks:
    -   id: git-diff # For reference: https://github.com/pre-commit/pre-commit/issues/1712
        name: When pre-commit fixers made changes, run 'git diff' to show the changes
        entry: git diff --exit-code
        language: system
        pass_filenames: false
        always_run: true
