include $(ROOT)/build/common.mk

NAME      := nested-svm
CATEGORY  := in-development
TEST-ENVS := $(HVM_ENVIRONMENTS)

TEST-EXTRA-CFG := extra.cfg.in

obj-perenv += main.o

include $(ROOT)/build/gen.mk
