name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        arch: [x86]
        compiler: [llvm-12, llvm-13, llvm-14]

        include:
          - arch: x86
            compiler: gcc-9
          - arch: x86
            compiler: gcc-10
          - arch: x86
            compiler: gcc-11
          - arch: x86
            compiler: gcc-12
          - arch: x86
            compiler: gcc-13

          - arch: x86
            compiler: clang-12
          - arch: x86
            compiler: clang-13
          - arch: x86
            compiler: clang-14

    runs-on: ubuntu-22.04

    steps:
    - name: Install
      run: |
        c=${{matrix.compiler}}
        v=${c##llvm-}
        case $c in
            # Need all {llvm,clang,lld}-$v packages
            llvm-*) EXTRA="clang-${v} lld-${v}" ;;
        esac

        sudo apt-get update -q
        sudo apt-get install -y build-essential python3 ${{matrix.compiler}} ${EXTRA}

    - uses: actions/checkout@v3

    - name: Build
      run: |
        # Select appropriate LLVM= or CC=
        c=${{matrix.compiler}}
        case $c in
            llvm-*)  COMP="LLVM=${c#llvm}" ;;
            *)       COMP="CC=$c" ;;
        esac

        make -j`nproc` ARCH=${{matrix.arch}} $CROSS $COMP
