name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        compiler: [gcc-7, gcc-8, gcc-9, gcc-10, clang-9, clang-10]
        lto: [lto=y, lto=n]

    runs-on: ubuntu-latest

    steps:
    - name: Install
      run: |
        sudo apt-get update -q
        sudo apt-get install ${{ matrix.compiler }}

    - uses: actions/checkout@v2

    - name: build
      run: |
        make -j `nproc` CC=${{matrix.compiler}} ${{matrix.lto}}
