name: build

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        arch: [x86]
        compiler: [llvm-9, llvm-10, llvm-11]

        include:
          - arch: x86
            compiler: gcc-7
          - arch: x86
            compiler: gcc-8
          - arch: x86
            compiler: gcc-9
          - arch: x86
            compiler: gcc-10

          - arch: x86
            compiler: clang-9
          - arch: x86
            compiler: clang-10
          - arch: x86
            compiler: clang-11

    runs-on: ubuntu-latest

    steps:
    - name: Install
      run: |
        # LLVM package does not contain clang and ld.lld
        c=${{matrix.compiler}}
        v=${c##llvm-}
        case $c in
            llvm-*) EXTRA="clang-${v} lld-${v}" ;;
        esac

        sudo apt-get update -q
        sudo apt-get install -y \
          ${{matrix.compiler}}  \
          build-essential       \
          python                \
          ${EXTRA}

    - uses: actions/checkout@v2

    - name: Build
      run: |
        # Select appropriate LLVM= or CC=
        c=${{matrix.compiler}}
        case $c in
            llvm-*)  COMP="LLVM=${c#llvm}" ;;
            *)       COMP="CC=$c" ;;
        esac

        make -j`nproc` ARCH=${{matrix.arch}} $CROSS $COMP
